### ISSUE TITLE
兄弟我像换starcoder2做代码补全，不用deepseek，配置是这样配置么，我也用的ollama

### ISSUE THREAD

**Issue by snowflake-Zhao** [foryoung365/vs-extension-llmcopilot#11]
![微信图片_20240912092506](https://github.com/user-attachments/assets/994c3590-8bba-4963-b841-fc8368475075)

**Comment by foryoung365** [comment]
base url是你ollama的地址和端口，请确认你的ollama运行在8091端口，默认应该是11434
两个model配置成一样，你需要确认这个模型同时支持聊天和代码补全（大部分模型的base支持补全，而instruct支持聊天）
然后根据你的模型修改 fim tokens，每个模型对应的token都可能不同，你需要去对应模型的model card或者token列表中查询。
