### ISSUE TITLE
get it work in VS2017?

### ISSUE THREAD

**Issue by d00m4ace** [foryoung365/vs-extension-llmcopilot#2]
hi thanks a lot for 2022 and 2019
but is't possible to get it work in VS2017?

**Comment by foryoung365** [comment]
After some searching, I found that vs2017 can support dotnet framework 4.7.2, [here](https://learn.microsoft.com/en-us/visualstudio/releases/2017/vs2017-compatibility-vs).
I tried to add support for vs2017, but I don't have an instance of vs2017. Do you mind helping me test if it works properly?
You may need install [dotnet framework 4.7.2](https://dotnet.microsoft.com/en-us/download/dotnet-framework) to get it to work.

[LLMCopilot_vs2017-2019.zip](https://github.com/user-attachments/files/15551695/LLMCopilot_vs2017-2019.zip)

**Comment by d00m4ace** [comment]
I try on my Visual Studio Professional 2017 :
![image](https://github.com/foryoung365/vs-extension-llmcopilot/assets/98466489/010d6b40-27a1-4f6c-a9c2-bdc739a3a479)

Microsoft Visual Studio Professional 2017 
Version 15.9.62
VisualStudio.15.Release/15.9.62+34830.200
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Professional

Visual C++ 2017   00370-10000-00000-AA941
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.61435.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.62002.01090
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   15.9.51025.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

**Comment by d00m4ace** [comment]
![image](https://github.com/foryoung365/vs-extension-llmcopilot/assets/98466489/02102f8a-4f2b-4a3f-9b16-8d815cb38813)
i try and install also dotnet framework 4.7.2
but as you can see option is gray

**Comment by foryoung365** [comment]
Thank you for your feedback, it seems there are other dependencies that have not been resolved, I will further investigate later this week.

**Comment by d00m4ace** [comment]
> Thank you for your feedback, it seems there are other dependencies that have not been resolved, I will further investigate later this week.

Thanks, let me know if I can help.

**Comment by foryoung365** [comment]
[LLMCopilot_vs2017_2019_v2.zip](https://github.com/user-attachments/files/15613828/LLMCopilot_vs2017_2019_v2.zip)
I made some adjustments again, could you please try this version?

**Comment by d00m4ace** [comment]
![image](https://github.com/foryoung365/vs-extension-llmcopilot/assets/98466489/e60700ed-ca9d-4a85-8e59-c24e137662f0)

**Comment by d00m4ace** [comment]
Thanks for all the work you've done! Sorry for the delay. I've been busy here.
The plugin is installed.
I will test c/c++ in VS2017 on ollame and Codestel and post a review later.
Thanks again!

**Comment by d00m4ace** [comment]
[ActivityLog.zip](https://github.com/user-attachments/files/15786744/ActivityLog.zip)
![image](https://github.com/foryoung365/vs-extension-llmcopilot/assets/98466489/bc69aa41-f7f0-4361-9338-9abd6a3a3e82)
Unfortunately, after installing and opening VS2017
I got this error

**Comment by d00m4ace** [comment]
![image](https://github.com/foryoung365/vs-extension-llmcopilot/assets/98466489/e6d3323c-4ab9-4b09-8359-116045a20ebf)

**Comment by d00m4ace** [comment]
> I have made some more modifications, please try again. I hope this time it will work. [LLMCopilot_vs2017_2019_v3.zip](https://github.com/user-attachments/files/15814674/LLMCopilot_vs2017_2019_v3.zip)

Uh-huh.
It's installed!
Now I'll try it with ollama one of these days. 
and I'll let you know.
once again respect and for your hard work)!

**Comment by foryoung365** [comment]
I'm glad to hear that you were able to successfully install it in VS2017, looking forward to your test results.
If everything goes well, I will release it to the marketplace as soon as possible.

**Comment by d00m4ace** [comment]
> I'm glad to hear that you were able to successfully install it in VS2017, looking forward to your test results. If everything goes well, I will release it to the marketplace as soon as possible.

Thank you! I'll try to test it better during this week and I'll be sure to report back.

**Comment by d00m4ace** [comment]
![image](https://github.com/foryoung365/vs-extension-llmcopilot/assets/98466489/fb7450bb-1269-4dcf-aeec-cdc3eaf68c93)

**Comment by d00m4ace** [comment]
Thank you! It works under VS2017!

But there are some questions)

I noticed that it often outputs code with Chinese text.
In the settings it is English but it doesn't change anything.
Second, what context window is used in the model by default?
Can it be set separately?

What code does LLm see? Is the code of all open windows passed with the code as in GitHub Copilot?

Is there any way to control it?

Thanks for your hard work!

I think it's ready to release!

Translated with DeepL.com (free version)

**Comment by foryoung365** [comment]
1. The language settings in the setup page only affect the responses to commands bundled with the extension, such as "explain code", "find bug", etc. If you communicate with it through the chat window, the default language depends on the model itself, such as "deepseek-coder" which is a model trained by a Chinese company and may tend to answer in Chinese. In this case, you can add "Answer in English" at the end of the prompt to request the LLM model to answer in English, and the same applies to other languages. Whether specific languages are supported depends on the LLM model itself.
2. In the current version, a 2K context window is used for code completion to achieve better average performance. The content window for the dialogue depends on the settings in the Ollama model file, and the extension will automatically initialize upon VS startup according to Ollama's settings. There is currently no support for setting adjustments. For specifics, please refer to the [Ollama documentation](https://github.com/ollama/ollama/blob/main/docs/modelfile.md).
3. In the current version, code completion only applies to the code in the active editing window. Settings are not supported.

The new version will be updated to the marketplace within this week
