### ISSUE TITLE
建议增加生成单元测试代码

### ISSUE THREAD

**Issue by lison666** [foryoung365/vs-extension-llmcopilot#4]
如题，对所选的代码生成单元测试，最好是全自动化生成cs文件

**Comment by foryoung365** [comment]
建议会纳入后续更新计划，但是鉴于本地大模型的能力，生成的结果不要有太高的期待。

**Comment by foryoung365** [comment]
生成单元测试代码的功能已发布在v1.5.x版本中，可以从VS扩展或者markplace中下载更新。
