### ISSUE TITLE
No support for LM Studio API?

### ISSUE THREAD

**Issue by maxim-stratan** [foryoung365/vs-extension-llmcopilot#5]
Can't find any documentation related to the suport of LM Studio API running deepseek coder

**Comment by foryoung365** [comment]
Sorry, but this extension currently focuses on using Ollama as the backend, and there are no plans to support LM Studio at the moment

**Comment by woaidianqian** [comment]
国产大模型deepseek coder能力接近gpt4，不支持有点可惜了，其实就是添加一个token输入的接口，工作量应该也不大，感谢。

**Comment by foryoung365** [comment]
> 国产大模型deepseek coder能力接近gpt4，不支持有点可惜了，其实就是添加一个token输入的接口，工作量应该也不大，感谢。

Ollama已经支持了deepseek-coder和deepseek-coder-v2，我在扩展说明页也写了推荐的大模型是deekseek-coder，所以我不太理解deepseek-coder的能力如何和是否支持LM Studio的关系是什么？

**Comment by woaidianqian** [comment]
> > 国产大模型deepseek coder能力接近gpt4，不支持有点可惜了，其实就是添加一个token输入的接口，工作量应该也不大，感谢。
> 
> Ollama已经支持了deepseek-coder和deepseek-coder-v2，我在扩展说明页也写了推荐的大模型是deekseek-coder，所以我不太理解deepseek-coder的能力如何和是否支持LM Studio的关系是什么？

我的意思是支持deepseek的官方api，就是需要输入token的那种，不是说ollama中的模型。

**Comment by foryoung365** [comment]
这个插件诞生的目的是为了解决在本地使用大模型的需求，对于需要联网的大模型平台，我相信你有更好的选择，比如CodeGeeX插件。
目前插件功能深度使用了Ollama Api的自定义参数，csharp下目前也没有一个好用的能支持各种LLM平台的通用连接库，所以目前不会考虑接入其他大模型平台。
另外这些讨论已经偏离了这个issue原本的主题，我将先关闭这个issue，如果还有别的问题，欢迎另开issue讨论。
